COLOR = {
    'Revenue': '#FF0000',
    'Gross Profit': '#FFA500',
    'EBITDA': '#FFFF00',
    'Net Profit': '#00FF00',
    'EPS': '#00FFFF',
    'ROE': '#0000FF',
    'ROA': '#800080',
    'Cash Flow': '#FF00FF',
    'Gross Profit Margin': '#2ca02c',
    'EBIT Margin': '#ff7f0e',
    'Net Profit Margin': '#d62728',
    'Current Ratio': '#9467bd',
    'Quick Ratio': '#8c564b',
    'Debt to Equity': '#e377c2',
    'Debt to Asset': '#7f7f7f',
    'Interest Coverage Ratio': '#bcbd22',
    'Inventory Turnover': '#17becf',
    'Receivable Turnover': '#1f77b4',
    'Payable Turnover': '#aec7e8',
    'Total Asset Turnover': '#ffbb78',
    'Fixed Asset Turnover': '#98df8a',
    'Equity Turnover': '#ff9896',
    'Days Inventory': '#c5b0d5',
    'Days Receivable': '#c49c94',
    'Days Payable': '#f7b6d2',
    'Days Sales in Inventory': '#c7c7c7',
    'Days Sales in Receivable': '#dbdb8d',
    'Days Sales in Payable': '#9edae5',
    'Cash Conversion Cycle': '#ad494a',
}